approvedGitRepositories:
  - '**'

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 3

npmPreapprovedPackages:
  - '@planttheidea/*'
